version: '2'
services:
  wpe:
    restart: always
    build: ./wpe
    depends_on:
      - nextcloud
    privileged: true
    network_mode: host
  nextcloud:
    restart: always
    build: ./nextcloud-proxy
    ports:
      - "9000:9000"
    expose: 
      - "9000"
    network_mode: host
  scheduler:
    restart: always
    build: ./scheduler
    privileged: true
